---
# tasks file for Docker install

- name: "Testing installed Docker"
  stat:
    path: /usr/bin/docker
  register: docker_exist
  ignore_errors: True

- name: "Add Docker GPG apt key"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: docker_exist.stat.exists == False

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
    filename: docker
    update_cache: yes
  when: docker_exist.stat.exists == False

- name: Install Docker packages
  package: 
    name: [ 'docker-ce', 'docker-ce-cli', 'containerd.io' ]
    state: latest
  when: docker_exist.stat.exists == False

- name: Add user ansible to Docker group
  user:
    name: "{{ docker_user }}"
    groups: docker
    append: yes

- name: Start Docker 
  service:
    name: docker
    state: started
    enabled: yes






