---
# tasks file for Docker install
- name: Install requered packages
  package: 
    name: [ 'apt-transport-https', 'ca-certificates', 'curl', 'gnupg', 'lsb-release' ]
    state: present

- name: Add Docker GPG apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Update packages
  apt:
    update_cache: yes

- name: Install Docker packages
  package: 
    name: [ 'docker-ce', 'docker-ce-cli', 'containerd.io' ]
    state: present

- name: Add user ansible to Docker group
  user:
    name: ansible
    groups: docker
    append: yes

- name: Start Docker 
  service:
    name: docker
    state: started
    enabled: yes






