---
# tasks file for Grafana

- name: "Install packages"
  package:
    name: [ 'apt-transport-https', 'software-properties-common' ]
    state: latest

- name: "Add Grafana apt key" 
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: "Add Grafana repository"
  apt_repository: 
    repo: deb https://packages.grafana.com/enterprise/deb stable main
    state: present
    filename: grafana
    update_cache: yes

- name: "Install Grafana Enterprise"
  package:
    name: grafana-enterprise
    state: latest

- name: "Start Grafana service"
  service:
    name: grafana-server
    daemon_reload: yes
    enabled: yes
    state: restarted


