---
# tasks file for kubernetes-workers-setup

- name: "Reset kubeadm if present"
  shell: kubeadm reset -f
  register: kubeadm_reset

- name: "Set kubeadm cgroupfs in config file"
  lineinfile:
    path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    line: Environment="cgroup-driver=systemd/cgroup-driver=cgroupfs"
    state: present

- name: "Generate worker join token"
  shell: kubeadm token create --print-join-command
  register: kubeadm_join_cmd
  delegate_to: "{{ kubernetes_first_master_dns }}"

- set_fact:
    kubeadm_join: "{{ kubeadm_join_cmd.stdout }}"

- name: Join Master replicas to cluster
  shell: "{{ kubeadm_join }}"

