---
# tasks file for kubernetes-masters-setup

- name: "Install Kubernetes packages"
  package:
    name: [ 'kubelet', 'kubeadm', 'kubectl', 'kubernetes-cni' ]
    state: latest

- name: "Reset kubeadm if present"
  shell: kubeadm reset -f
  register: kubeadm_reset


- name: "Generate kubeadm token"
  command: kubeadm token generate
  register: token_generation

- set_fact:
    kubeadm_token: "{{ token_generation.stdout }}"

- debug:
    msg: "{{ kubeadm_token }}"




#- name: "Setup kubeadm for master"
#  shell: kubeadm ini --apiserver-advertise-address=10.1.33.21 --token="{{ kubeadm_token }}" --pod-*network-cidr="{{ kubernetes_pod_subnet }}"
#  register: kubeadm_init
#  when: kubeadm_reset is succeeded

- name: "root directory"
  shell: echo $HOME
  register: root_home

- name: ".kube directory creation"
  file:
    path: "{{ root_home.stdout }}/.kube/"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: "Generate kubeadm-config.yml"
  template:
    src: ../templates/kubeadm-config.yml
    dest: "{{ root_home }}.kube/kubeadm-config.yml


- name: "Generate /etc/kubernetes/admin.conf"
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "{{ root_home.stdout }}/.kube/config"
    owner: root
    group: root
    mode: 0600
    remote_src: yes
    backup: yes
  when: kubeadm_init

- name: "Restart kubelet"
  systemd:
    name: kubelet
    state: restarted
    daemon_reload: yes
    enabled: yes
