---
# tasks for Kubernetes network setting

- name: changement de conf pour les bridges
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    state: present

- name: Enable ip forwarding on IPv4 and reload if necessary
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes




