---
# Kubernetes k8s installation Playbook
- name: "Common installation"
  hosts: none # all
  become: yes
  gather_facts: true
  roles:
    - role: "system/update"
    - role: "system/upgrade"
    - role: "system/common-packages"
    - role: "rasberry/rasberry-remove-swap"

- name: "Common kubernetes installation"
  hosts: none # [k8s-admin, nodes]
  vars:
    docker_user: ansible
  become: yes
  gather_facts: true
  roles:
    - role: "k8s/kubernetes-common-packages"
    - role: "k8s/kubernetes-add-repository"


- name: "Ha-Proxy installation"
  hosts: none # haproxy
  vars:
    haproxy_user_login: ansible
    haproxy_user_password: ansible
  become: yes
  gather_facts: true
  roles:
    - role: "k8s/haproxy-install"


- name: "Docker installation"
  hosts: none # nodes
  vars:
    docker_user: ansible
    cmdline_path: /boot/firmware/cmdline.txt
  become: yes
  gather_facts: true
  roles:
    - role: "rasberry/rasberry-set-cgroup"
    - role: "k8s/docker-install"
    - role: "k8s/kubernetes-network" 


- name: "Control plane setup"
  hosts: none # k8s-master-01
  vars:
    kubernetes_pod_subnet: "192.168.0.0/16"
    load_balancer_ip: 10.1.33.20
    load_balancer_port: 6443
  become: yes
  gather_facts: false
  roles:
    - role: "k8s/kubernetes-masters-setup"


- name: "Workers setup"
  hosts: none # k8s-worker-01
  vars:
    kubernetes_pod_subnet: "192.168.0.0/16"
    load_balancer_ip: 10.1.33.20
    load_balancer_port: 6443
  become: yes
  gather_facts: false
  roles:
    - role: "k8s/kubernetes-workers-setup"


- name: "CLI installation on admin server"
  hosts: none # [ k8s-master-01, k8s-admin ]
  vars:
    kube_host_src: k8s-master-01
    kubernetes_host_cli: k8s-admin
  gather_facts: false
  roles:
    - role: "k8s/kubernetes-cli-install"
