---
- hosts: cluster
  become: yes
  gather_facts: true
  tasks:
    - name: Update server
      apt:
        update_cache=yes
        cache_valid_time=86400

    - name: Upgrade server
      apt:
        upgrade=yes
