---
# Add Kubernetes repository and update packages

- name: "Install Kubernetes cli packages"
  package:
    name: kubectl
    state: latest
  when: inventory_hostname == kubernetes_host_cli

- name: "Copy .kube directory files from k8s-master-01"
  synchronize:
    src: /home/ansible/.kube/
    dest: /home/ansible/.kube
    mode: pull
  when: inventory_hostname == kube_host_src
